# Based copy from: https://github.com/wl4g/rengine/blob/master/service/src/main/resources/application.yaml
# Copyright (c) 2017 ~ 2025, the original author James Wong individual Inc,
# All rights reserved. Contact us <jameswong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

spring:
  application.name: x-ops
  profiles:
    active: dev
  banner:
    location: classpath:META-INF/banner.txt
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8000
  servlet:
    contextPath: /
    session:
      timeout: 30m
      cookie:
        name: __r_sid
    tomcat: # see: org.springframework.boot.autoconfigure.web.ServerProperties.Tomcat
      basedir: /tmp/${spring.application.name}/
      accesslog:
        enabled: false
        directory: ${server.tomcat.basedir}/log/${spring.application.name}/ # Directory in which log files are created. Can be absolute or relative to the Tomcat base dir.
        requestAttributesEnabled: false # Set request attributes for the IP address, Hostname, protocol, and port used for the request.
      backgroundProcessorDelay: 1000 # default: 10s
      thread:
        # Maximum amount of worker threads. for example 4C 8G, and the empirical value of thread number is 800. The operating system
        # has system overhead for switching and scheduling between threads, so not the more the better. The minimum number of idle working threads
        # is 10 by default. (increase it appropriately to cope with the sudden increase of visits). default: 200
        max: 10
        min-spare: 2 # Minimum amount of worker threads. default: 10
      # Maximum number of connections that the server accepts and processes at any given time. Once the limit has been reached, the
      # operating system may still accept connections based on the "acceptCount" property. default: 8192
      maxConnections: 8192
      # Maximum queue length for incoming connection requests when all possible request processing threads are in use. defualt: 100
      accept-count: 100
      # Maximum number of idle processors that will be retained in the cache and reused with a subsequent request. When set to -1
      # the cache will be unlimited with a theoretical maximum size equal to the maximum number of connections. default: 200
      processorCache: 200
      maxHttpFormPostSize: 2MB # Maximum size of the form content in any HTTP post request.
      maxSwallowSize: 2MB # Maximum amount of request body to swallow.
      uri-encoding: UTF-8
      mbeanregistry:
        enable: true
      remoteip:
        remoteIpHeader: X-Forwarded-For
        protocolHeader: X-Forwarded-Proto
        hostHeader: X-Forwarded-Host
        portHeader: X-Forwarded-Port

#  redis:
#    #username:
#    password: 123456
#    ssl: false
#    database: 0
#    timeout: 10s
#    connectTimeout: 5s
#    #clientName:
#    clientType: LETTUCE
#    cluster:
#      nodes:
#        - localhost:6379
#        - localhost:6380
#        - localhost:6381
#        - localhost:7379
#        - localhost:7380
#        - localhost:7381
#      max-redirects: 3
#    lettuce:
#      shutdownTimeout: 1s
#      pool:
#        enabled: true
#        maxIdle: 8
#        minIdle: 0
#        maxActive: 8
#        maxWait: 3_000
#        timeBetweenEvictionRuns: 2h
#      cluster:
#        refresh:
#          dynamicRefreshSources: true
#          period: 60s
#          adaptive: true

  devtools:
    #add-properties: false ## Default by true
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
      log-condition-evaluation-delta: false
      exclude: static/**,public/**